/*
 * tristate_l5_strong.c — TD-5 L5 strong-claim cycle (REMEDIATED 2026-05-06).
 *
 * Per docs/TECHNICAL_DEBT.md TD-5 + journal/tristate_strong_closeout.md
 * Track C ("Cross-exp accum strong-claim L5: requires residual-style
 * workload not produced by GEMM-only").
 *
 * REMEDIATION RC-1: original v1 (committed c404ef6) was misnamed — the bench
 * used plain int32 addition (Y_post = Y_pre + R) and never invoked the
 * substrate's cross-exp primitive `m4t_mtfp_vec_accum_aligning`. v1 results
 * therefore tested generic ternary-residual cancellation, not cross-exp accum.
 *
 * v2 (this file) calls m4t_mtfp_vec_accum_aligning with explicit exponents
 * to exercise the substrate's actual cross-exp primitive and isolate the
 * exponent-alignment effect on the third state.
 *
 * REMEDIATION RC-12: v1's R = -α·Y_pre + noise was an unnaturally tight
 * anti-correlation with the previous layer; real ML residuals are y = f(x)
 * + x where f is independent. v2 keeps the cancellation regimes for
 * comparability but adds an honest "skip-connection" regime where R is
 * generated by an INDEPENDENT second matmul X1' @ W1' of the same shape
 * (no enforced anti-correlation).
 *
 * Workload pattern:
 *   Y_pre = X1 @ W1                                    (ternary GEMM, int32 mantissas, exp=0)
 *   R = generated per regime                           (int32 mantissas, exp=eR)
 *   m4t_mtfp_vec_accum_aligning(Y_pre, &eA, R, eR, ..., n)
 *     → Y_pre now holds aligned sum at unified exp
 *   X2 = ternarize(Y_pre, p_zero)
 *   Y2 = X2 @ W2
 *
 * Third state at L5 = cells where (aligned cross-exp sum) == 0. Three
 * sub-cases captured (informational, not separately measured):
 *   - structural cancellation (a + b == 0 in aligned space)
 *   - alignment-induced decay (smaller-exp side rounded to zero, the other
 *     side was already zero or balanced to zero)
 *   - trivial double-zero
 *
 * Gate II measurement (cohort = cells where Y_post == 0): collapse cohort
 * (force ±1 in X2), compute cos(Y2_native, Y2_collapsed).
 *
 * Pre-committed thresholds: cos < 0.85 LOAD-BEARING; 0.85-0.95 MIXED;
 * cos ≥ 0.95 SINK.
 */

#include "m4t_mtfp.h"
#include "m4t_types.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <assert.h>

/* ── Helpers (RC-13: kept inline for now; refactor pending) ──────────── */
typedef struct { uint32_t s; } rng_t;
static void rng_init(rng_t* r, uint32_t seed) { r->s = seed ? seed : 0xdeadbeefu; }
static uint32_t rng_u32(rng_t* r) {
    uint32_t x = r->s;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    r->s = x;
    return x;
}
static int rng_sign(rng_t* r) { return (rng_u32(r) & 1u) ? 1 : -1; }
static int rng_lt(rng_t* r, double p) {
    return ((double)(rng_u32(r) & 0xFFFFFFu) / (double)0x1000000) < p;
}
static int rng_range(rng_t* r, int lo, int hi) {
    return lo + (int)(rng_u32(r) % (uint32_t)(hi - lo + 1));
}
static void gen_ternary(m4t_trit_t* dst, int n, double p_zero, rng_t* r) {
    for (int i = 0; i < n; i++)
        dst[i] = rng_lt(r, p_zero) ? 0 : (m4t_trit_t)rng_sign(r);
}
static void matmul_ternary(
    m4t_mtfp_t* Y, const m4t_trit_t* X, const m4t_trit_t* W,
    int M, int K, int N)
{
    for (int i = 0; i < M; i++)
    for (int j = 0; j < N; j++) {
        int acc = 0;
        const m4t_trit_t* xi = X + (size_t)i * K;
        const m4t_trit_t* wj = W + (size_t)j * K;
        for (int k = 0; k < K; k++) acc += (int)xi[k] * (int)wj[k];
        Y[(size_t)i * N + j] = (m4t_mtfp_t)acc;
    }
}
static void shellsort_int(int* a, int n) {
    for (int gap = n / 2; gap > 0; gap /= 2)
        for (int i = gap; i < n; i++) {
            int tmp = a[i], j = i;
            while (j >= gap && a[j - gap] > tmp) { a[j] = a[j - gap]; j -= gap; }
            a[j] = tmp;
        }
}
static void ternarize_quantile(
    m4t_trit_t* dst, const m4t_mtfp_t* src, int n, double p_zero)
{
    int* abs_vals = (int*)malloc((size_t)n * sizeof(int));
    for (int i = 0; i < n; i++) {
        int v = src[i]; abs_vals[i] = (v < 0) ? -v : v;
    }
    shellsort_int(abs_vals, n);
    int idx = (int)((double)n * p_zero);
    if (idx >= n) idx = n - 1;
    if (idx < 0)  idx = 0;
    int tau = abs_vals[idx];
    free(abs_vals);
    for (int i = 0; i < n; i++) {
        int v = src[i]; int absv = (v < 0) ? -v : v;
        if (absv <= tau) dst[i] = 0;
        else             dst[i] = (m4t_trit_t)((v > 0) ? 1 : -1);
    }
}
static double cosine_sim_int(const m4t_mtfp_t* a, const m4t_mtfp_t* b, int n) {
    long long dot = 0, sa = 0, sb = 0;
    for (int i = 0; i < n; i++) {
        long long ai = a[i], bi = b[i];
        dot += ai * bi; sa += ai * ai; sb += bi * bi;
    }
    if (sa == 0 || sb == 0) return 1.0;
    return (double)dot / (sqrt((double)sa) * sqrt((double)sb));
}

/* ── Residual generators ───────────────────────────────────────────────── */
typedef enum {
    REGIME_CANCEL_50  = 0,
    REGIME_CANCEL_90  = 1,
    REGIME_INDEPENDENT = 2,
    REGIME_DECAY      = 3,
    REGIME_SKIP_CONN  = 4,   /* RC-12: honest skip-connection (independent matmul) */
} regime_t;
static const char* REGIME_NAME[] = {
    "cancel 50%", "cancel 90%", "independent", "decay (small)", "skip-conn (real)"
};
#define N_REGIMES 5

/* For SKIP_CONN: caller passes a pre-computed independent matmul result
 * via R. For other regimes, this function generates R directly. */
static void gen_residual(
    m4t_mtfp_t* R, const m4t_mtfp_t* Y_pre, int n,
    regime_t regime, rng_t* rng)
{
    switch (regime) {
        case REGIME_CANCEL_50:
            for (int i = 0; i < n; i++) {
                int noise = rng_range(rng, -3, 3);
                R[i] = (m4t_mtfp_t)(-Y_pre[i] / 2 + noise);
            }
            break;
        case REGIME_CANCEL_90:
            for (int i = 0; i < n; i++) {
                int noise = rng_range(rng, -2, 2);
                R[i] = (m4t_mtfp_t)(-(int)((double)Y_pre[i] * 0.9) + noise);
            }
            break;
        case REGIME_INDEPENDENT:
            for (int i = 0; i < n; i++) R[i] = (m4t_mtfp_t)rng_range(rng, -50, 50);
            break;
        case REGIME_DECAY:
            for (int i = 0; i < n; i++) R[i] = (m4t_mtfp_t)rng_range(rng, -1, 1);
            break;
        case REGIME_SKIP_CONN:
            /* Caller fills R via independent matmul; do nothing. */
            break;
    }
}

/* ── Per-(regime, Δexp) measurement ─────────────────────────────────────── */
typedef struct {
    double cos;
    int    n_zero_post;        /* cells where Y_post == 0 (the L5 cohort) */
    int    n_x2_zero;          /* total X2 == 0 cells */
} L5Result;

/* Δ_exp = (running_exp_input - addend_exp). Negative Δ → addend has bigger
 * exp, running gets rescaled DOWN. Positive Δ → addend rescaled DOWN.
 * Δ = 0 → no alignment. */
static L5Result measure_l5(
    int M, int K, int N, int P,
    double w_zero, double a_zero, double a_zero_post,
    uint32_t seed, regime_t regime, int delta_exp)
{
    L5Result out = { 0 };
    m4t_trit_t* X1 = (m4t_trit_t*)calloc((size_t)M*K, sizeof(m4t_trit_t));
    m4t_trit_t* W1 = (m4t_trit_t*)calloc((size_t)N*K, sizeof(m4t_trit_t));
    m4t_trit_t* W2 = (m4t_trit_t*)calloc((size_t)P*N, sizeof(m4t_trit_t));
    m4t_mtfp_t* Y_pre  = (m4t_mtfp_t*)calloc((size_t)M*N, sizeof(m4t_mtfp_t));
    m4t_mtfp_t* R      = (m4t_mtfp_t*)calloc((size_t)M*N, sizeof(m4t_mtfp_t));
    /* For SKIP_CONN regime: independent X1', W1' for second matmul. */
    m4t_trit_t* X1_skip = (m4t_trit_t*)calloc((size_t)M*K, sizeof(m4t_trit_t));
    m4t_trit_t* W1_skip = (m4t_trit_t*)calloc((size_t)N*K, sizeof(m4t_trit_t));
    m4t_trit_t* X2_native = (m4t_trit_t*)calloc((size_t)M*N, sizeof(m4t_trit_t));
    m4t_trit_t* X2_test   = (m4t_trit_t*)calloc((size_t)M*N, sizeof(m4t_trit_t));
    m4t_mtfp_t* Y2_native = (m4t_mtfp_t*)calloc((size_t)M*P, sizeof(m4t_mtfp_t));
    m4t_mtfp_t* Y2_test   = (m4t_mtfp_t*)calloc((size_t)M*P, sizeof(m4t_mtfp_t));
    /* Snapshot of Y_pre before cross-exp accum, used for cohort labeling. */
    m4t_mtfp_t* Y_post_snapshot = (m4t_mtfp_t*)calloc((size_t)M*N, sizeof(m4t_mtfp_t));

    rng_t rng; rng_init(&rng, seed);
    gen_ternary(X1, M*K, a_zero, &rng);
    gen_ternary(W1, N*K, w_zero, &rng);
    gen_ternary(W2, P*N, w_zero, &rng);
    gen_ternary(X1_skip, M*K, a_zero, &rng);
    gen_ternary(W1_skip, N*K, w_zero, &rng);

    matmul_ternary(Y_pre, X1, W1, M, K, N);

    /* Generate R per regime. */
    if (regime == REGIME_SKIP_CONN) {
        /* RC-12: honest skip-connection — R from independent matmul. */
        matmul_ternary(R, X1_skip, W1_skip, M, K, N);
    } else {
        gen_residual(R, Y_pre, M*N, regime, &rng);
    }

    /* Bound check — kernel asserts |running|, |addend| <= MAX_VAL (581M).
     * Our matmul outputs are |.| <= K <= 4096 ≪ MAX_VAL; gen_residual
     * outputs in {-1,..50} or {-512..512}. All safe. */

    /* RC-1 REMEDIATION: actually invoke the cross-exp primitive. */
    int8_t running_exp = 0;
    int8_t addend_exp = (int8_t)(running_exp - delta_exp);  /* delta_exp = running − addend */
    m4t_mtfp_vec_accum_aligning(Y_pre, &running_exp, R, addend_exp, NULL, M*N);
    /* Y_pre now holds the aligned cross-exp sum at *running_exp. */
    memcpy(Y_post_snapshot, Y_pre, (size_t)M*N * sizeof(m4t_mtfp_t));

    int n_zero_post = 0;
    for (int i = 0; i < M*N; i++) if (Y_post_snapshot[i] == 0) n_zero_post++;
    out.n_zero_post = n_zero_post;

    /* Ternarize Y_post → X2. */
    ternarize_quantile(X2_native, Y_post_snapshot, M*N, a_zero_post);
    int n_x2_zero = 0;
    for (int i = 0; i < M*N; i++) if (X2_native[i] == 0) n_x2_zero++;
    out.n_x2_zero = n_x2_zero;

    matmul_ternary(Y2_native, X2_native, W2, M, N, P);

    /* Collapse L5 cohort: force cells where Y_post == 0 (and X2 == 0) to ±1. */
    memcpy(X2_test, X2_native, (size_t)M*N * sizeof(m4t_trit_t));
    rng_t crng; rng_init(&crng, seed ^ 0x5555u);
    int n_collapsed = 0;
    for (int i = 0; i < M*N; i++) {
        if (X2_native[i] == 0 && Y_post_snapshot[i] == 0) {
            X2_test[i] = (m4t_trit_t)rng_sign(&crng);
            n_collapsed++;
        }
    }
    matmul_ternary(Y2_test, X2_test, W2, M, N, P);
    (void)n_collapsed;

    out.cos = cosine_sim_int(Y2_native, Y2_test, M*P);

    free(X1); free(W1); free(W2);
    free(Y_pre); free(R); free(X1_skip); free(W1_skip);
    free(X2_native); free(X2_test);
    free(Y2_native); free(Y2_test);
    free(Y_post_snapshot);
    return out;
}

/* ── Configs ────────────────────────────────────────────────────────────── */
typedef struct { int K; double w_zero, a_zero; } Config;
static const Config CONFIGS[] = {
    {  64, 0.20, 0.20 }, {  64, 0.60, 0.60 },
    { 256, 0.20, 0.20 }, { 256, 0.60, 0.60 },
    {1024, 0.20, 0.20 }, {1024, 0.60, 0.60 },
};
#define N_CONFIGS (int)(sizeof(CONFIGS)/sizeof(CONFIGS[0]))
#define N_SEEDS   5
#define M_BATCH   8
#define P_OUT     8
#define A_ZERO_POST 0.40

/* Δexp variants: 0 = same exp (no cross-exp), 1 = mild, 3 = stronger. */
static const int DELTAS[] = { 0, 1, 3 };
#define N_DELTAS (int)(sizeof(DELTAS)/sizeof(DELTAS[0]))

int main(void) {
    printf("# TD-5: L5 cross-exp accum strong-claim cycle (v2 — RC-1/RC-12 remediation)\n");
    printf("# %d configs × %d seeds × %d regimes × %d Δexp variants\n",
        N_CONFIGS, N_SEEDS, N_REGIMES, N_DELTAS);
    printf("# RC-1 fix: m4t_mtfp_vec_accum_aligning is now called with explicit exponents.\n");
    printf("# RC-12 fix: SKIP-CONN regime added (independent matmul, no anti-correlation).\n\n");

    /* Per-regime, per-Δexp aggregate. */
    double cos_table[N_REGIMES][N_DELTAS] = { {0} };
    double cohort_table[N_REGIMES][N_DELTAS] = { {0} };

    for (int reg = 0; reg < N_REGIMES; reg++) {
        printf("=== Regime %d: %s ===\n", reg, REGIME_NAME[reg]);
        printf("Δexp  K     w_z   a_z   |  cos        cohort_size\n");
        for (int di = 0; di < N_DELTAS; di++) {
            int delta = DELTAS[di];
            double sum_cos = 0.0, sum_coh = 0.0;
            int total = 0;
            for (int c = 0; c < N_CONFIGS; c++) {
                const Config* cfg = &CONFIGS[c];
                double mc = 0.0, mcoh = 0.0;
                for (int s = 0; s < N_SEEDS; s++) {
                    uint32_t seed = (uint32_t)(c+1) * 0x9E3779B1u
                                  ^ (uint32_t)(s+1) * 0x85EBCA6Bu
                                  ^ (uint32_t)(reg+1) * 0xC2B2AE3Du
                                  ^ (uint32_t)(di+1) * 0x27D4EB2Fu;
                    L5Result r = measure_l5(
                        M_BATCH, cfg->K, cfg->K, P_OUT,
                        cfg->w_zero, cfg->a_zero, A_ZERO_POST,
                        seed, (regime_t)reg, delta);
                    mc += r.cos; mcoh += r.n_zero_post;
                }
                mc /= N_SEEDS; mcoh /= N_SEEDS;
                sum_cos += mc; sum_coh += mcoh; total++;
                printf(" %d    %4d  %.2f  %.2f  |  %.6f   %7.1f\n",
                       delta, cfg->K, cfg->w_zero, cfg->a_zero, mc, mcoh);
            }
            sum_cos /= total; sum_coh /= total;
            cos_table[reg][di] = sum_cos;
            cohort_table[reg][di] = sum_coh;
            printf("MEAN  Δexp=%d              |  %.6f   %7.1f\n",
                delta, sum_cos, sum_coh);
        }
        printf("\n");
    }

    /* ── Verdict tables ─────────────────────────────────────────────────── */
    const double LOAD_LIMIT  = 0.85;
    const double MIXED_LIMIT = 0.95;
    #define TAG(c) ((c) < LOAD_LIMIT ? "LOAD" : \
                    (c) < MIXED_LIMIT ? "MIXED" : "SINK")

    printf("################################################################\n");
    printf("# Cross-exp accum verdict matrix — mean cos by (regime, Δexp)\n");
    printf("################################################################\n\n");
    printf("%-20s ", "regime");
    for (int di = 0; di < N_DELTAS; di++) printf("Δ=%d        ", DELTAS[di]);
    printf("\n");
    for (int reg = 0; reg < N_REGIMES; reg++) {
        printf("%-20s ", REGIME_NAME[reg]);
        for (int di = 0; di < N_DELTAS; di++) {
            printf("%.4f(%-4s) ", cos_table[reg][di], TAG(cos_table[reg][di]));
        }
        printf("\n");
    }
    printf("\n");

    /* Per-cell impact (RC-6 caveat: marked SUGGESTIVE — non-linear metric). */
    printf("Per-cell impact ((1-cos)/cohort × 10000) — SUGGESTIVE ONLY (non-linear):\n");
    printf("%-20s ", "regime");
    for (int di = 0; di < N_DELTAS; di++) printf("Δ=%d     ", DELTAS[di]);
    printf("\n");
    for (int reg = 0; reg < N_REGIMES; reg++) {
        printf("%-20s ", REGIME_NAME[reg]);
        for (int di = 0; di < N_DELTAS; di++) {
            double pci = cohort_table[reg][di] > 0
                ? (1.0 - cos_table[reg][di]) * 10000.0 / cohort_table[reg][di]
                : 0.0;
            printf("%6.3f   ", pci);
        }
        printf("\n");
    }
    printf("\n");

    /* Cross-exp effect: how does Δ change cos within each regime? */
    printf("################################################################\n");
    printf("# Cross-exp alignment effect (compare Δ=0 vs Δ=1, Δ=3)\n");
    printf("################################################################\n\n");
    for (int reg = 0; reg < N_REGIMES; reg++) {
        double base = cos_table[reg][0];
        printf("  %-20s  Δ=0 cos %.4f → Δ=1 %.4f (gap %+.4f) → Δ=3 %.4f (gap %+.4f)\n",
            REGIME_NAME[reg], base,
            cos_table[reg][1], cos_table[reg][1] - base,
            cos_table[reg][2], cos_table[reg][2] - base);
    }
    printf("\n");
    printf("Reading: gap > 0 means cross-exp alignment makes the third state\n"
           "LESS load-bearing (cos rises). gap < 0 means cross-exp makes it\n"
           "MORE load-bearing (cos drops).\n\n");

    /* Headline: the regime+Δ with lowest cos is most load-bearing. */
    int best_reg = 0, best_di = 0;
    for (int reg = 0; reg < N_REGIMES; reg++)
    for (int di = 0; di < N_DELTAS; di++) {
        if (cos_table[reg][di] < cos_table[best_reg][best_di]) {
            best_reg = reg; best_di = di;
        }
    }
    printf("Headline: lowest cos = %.4f at regime=%s Δ=%d\n",
        cos_table[best_reg][best_di], REGIME_NAME[best_reg], DELTAS[best_di]);

    return 0;
}
