/*
 * test_m4t_shift3_neon_proto.c — prototype NEON divide-by-3^k kernel
 * + bit-exact property test vs the substrate's scalar reference.
 *
 * Per session 2026-05-04 conversation: replace m4t_pow3_round_div hot
 * path with vmull_s32 + bias + shift for vectorized divide-by-3^k.
 *
 * Constants (M_table, N_table) were generated by m4t/tools/gen_pow3_magic.c
 * and verified bit-exact across the full [-MAX_VAL, +MAX_VAL] range there.
 * This test re-validates at the NEON-intrinsic level (i.e., what actually
 * runs on hardware) and adds a quick perf comparison.
 *
 * Build (prototype, not wired into ctest yet):
 *   cc -O3 -mcpu=native m4t/tests/test_m4t_shift3_neon_proto.c \
 *      build/m4t/libm4t.a -o /tmp/test_shift3_neon
 *   /tmp/test_shift3_neon
 */

#include "m4t_mtfp.h"
#include "m4t_types.h"
#include "m4t_pow3_magic.h"   /* G7: single source of truth for M/N tables */

#include <arm_neon.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define MAX_VAL 581130733  /* (3^19 - 1) / 2 */
#define M_table M4T_POW3_DIV_M
#define N_table M4T_POW3_DIV_N

/* NEON divide-by-3^k for k ∈ [1, 19].
 * Pipeline per 4 lanes:
 *   prod_64 = vmull_s32(x_lo_or_hi, M)       // 32x32 -> 64
 *   prod_64 += bias = 1 << (N-1)             // round-half-up
 *   prod_64 >>= N                             // arith shift right
 *   narrow to int32                          // take low 32 bits
 *
 * Notes:
 *   - vshlq_s64 with NEGATIVE shift = arith right shift (rounds toward -∞).
 *     Combined with the +bias, gives round-half-up overall = round-to-nearest
 *     for non-tie cases (and odd d means no ties for this kernel).
 *   - We split the int32x4 into two int32x2 halves because vmull_s32 takes
 *     int32x2 inputs and returns int64x2.
 *
 * G2 saturation argument (verified empirically — see /tmp/saturation_check):
 *   For x ∈ [-MAX_VAL, +MAX_VAL] (|x| ≤ 2^29.1) and our table M ≤ 2^31:
 *     |x*M|        ≤ 2^60.1
 *     |x*M + bias| ≤ 2^61.0   (worst case observed at k=19, x=±MAX_VAL)
 *                  < 2^63 = INT64_MAX            // 2-bit headroom; no int64 overflow
 *     |result|     ≤ |x|/d_min = MAX_VAL/3 ≈ 2^27.5
 *                  < 2^31 = INT32_MAX            // 3.47-bit headroom
 *   Therefore vmovn_s64 narrows correctly (the int64 value fits in int32). */
static void m4t_shift3_div_neon(m4t_mtfp_t* dst, const m4t_mtfp_t* src,
                                int abs_k, int n) {
    int32_t M = M_table[abs_k];
    int     N = N_table[abs_k];
    int32x2_t Mv = vdup_n_s32(M);
    int64x2_t bias = vdupq_n_s64((int64_t)1 << (N - 1));
    int64x2_t neg_N = vdupq_n_s64(-(int64_t)N);

    int i = 0;
    for (; i + 4 <= n; i += 4) {
        int32x4_t x = vld1q_s32((const int32_t*)(src + i));
        int64x2_t prod_lo = vmull_s32(vget_low_s32(x), Mv);
        int64x2_t prod_hi = vmull_s32(vget_high_s32(x), Mv);
        prod_lo = vaddq_s64(prod_lo, bias);
        prod_hi = vaddq_s64(prod_hi, bias);
        prod_lo = vshlq_s64(prod_lo, neg_N);
        prod_hi = vshlq_s64(prod_hi, neg_N);
        int32x4_t result = vcombine_s32(vmovn_s64(prod_lo), vmovn_s64(prod_hi));
        vst1q_s32((int32_t*)(dst + i), result);
    }
    /* Scalar tail. */
    for (; i < n; i++) {
        int64_t prod = (int64_t)src[i] * (int64_t)M;
        int64_t adj  = prod + ((int64_t)1 << (N - 1));
        dst[i] = (m4t_mtfp_t)(adj >> N);
    }
}

/* ── Tests ─────────────────────────────────────────────────────────────── */

static int g_fails = 0;

/* Test 1: bit-exact vs scalar reference at boundary points + random sample. */
static void test_bit_exact_per_k(int abs_k) {
    enum { N_RAND = 50000 };
    int n = N_RAND + 12 + 4; /* random + corners + tail */
    m4t_mtfp_t* in_buf  = malloc(n * sizeof(m4t_mtfp_t));
    m4t_mtfp_t* out_neon = malloc(n * sizeof(m4t_mtfp_t));
    m4t_mtfp_t* out_ref  = malloc(n * sizeof(m4t_mtfp_t));
    if (!in_buf || !out_neon || !out_ref) {
        fprintf(stderr, "malloc fail\n"); exit(1);
    }

    /* Corners. */
    int idx = 0;
    in_buf[idx++] = 0;
    in_buf[idx++] = 1;
    in_buf[idx++] = -1;
    in_buf[idx++] = (m4t_mtfp_t)MAX_VAL;
    in_buf[idx++] = (m4t_mtfp_t)(-MAX_VAL);
    in_buf[idx++] = (m4t_mtfp_t)(MAX_VAL - 1);
    in_buf[idx++] = (m4t_mtfp_t)(-MAX_VAL + 1);
    in_buf[idx++] = (m4t_mtfp_t)(MAX_VAL / 2);
    in_buf[idx++] = (m4t_mtfp_t)(-MAX_VAL / 2);
    in_buf[idx++] = 1000000;
    in_buf[idx++] = -1000000;
    in_buf[idx++] = 12345;

    /* Random. */
    srand(42 + abs_k);
    for (int j = 0; j < N_RAND; j++) {
        int64_t r = ((int64_t)rand() << 32) ^ rand();
        r = r % (2 * MAX_VAL + 1) - MAX_VAL;
        in_buf[idx++] = (m4t_mtfp_t)r;
    }
    /* Pad with zeros to make n_total a multiple of 4 plus a few. */
    for (; idx < n; idx++) in_buf[idx] = 0;

    /* NEON path: divide via the prototype kernel. */
    m4t_shift3_div_neon(out_neon, in_buf, abs_k, n);

    /* Reference path: substrate's m4t_mtfp_shift3 with k = -abs_k. */
    m4t_mtfp_shift3(out_ref, in_buf, -abs_k, n);

    /* Compare bit-exact. */
    int per_k_fails = 0;
    for (int i = 0; i < n; i++) {
        if (out_neon[i] != out_ref[i]) {
            per_k_fails++;
            if (per_k_fails <= 3) {
                fprintf(stderr,
                    "  k=%d FAIL i=%d in=%d neon=%d ref=%d\n",
                    abs_k, i, (int)in_buf[i], (int)out_neon[i], (int)out_ref[i]);
            }
        }
    }
    if (per_k_fails == 0) {
        printf("  k=%2d PASS  (%d cases bit-exact)\n", abs_k, n);
    } else {
        printf("  k=%2d FAIL  (%d / %d mismatches)\n", abs_k, per_k_fails, n);
        g_fails += per_k_fails;
    }

    free(in_buf); free(out_neon); free(out_ref);
}

/* G3: Aliasing test — confirm dst==src works.
 * Strategy: build expected[] via separate dst (no alias), then run kernel
 * in-place on a copy, compare. Run for boundary k and several n covering
 * NEON-aligned + tail. */
static void test_aliasing(void) {
    const int ks[] = {1, 10, 19};
    const int ns[] = {4, 5, 64, 65};
    int alias_fails = 0;
    for (size_t ki = 0; ki < sizeof(ks)/sizeof(ks[0]); ki++) {
        for (size_t ni = 0; ni < sizeof(ns)/sizeof(ns[0]); ni++) {
            int abs_k = ks[ki];
            int n = ns[ni];
            m4t_mtfp_t* src = malloc(n * sizeof(m4t_mtfp_t));
            m4t_mtfp_t* expected = malloc(n * sizeof(m4t_mtfp_t));
            m4t_mtfp_t* inplace = malloc(n * sizeof(m4t_mtfp_t));
            srand(7 * abs_k + n);
            for (int i = 0; i < n; i++) {
                int64_t r = ((int64_t)rand() << 32) ^ rand();
                src[i] = (m4t_mtfp_t)(r % (2 * MAX_VAL + 1) - MAX_VAL);
                inplace[i] = src[i];  /* copy for in-place run */
            }
            m4t_shift3_div_neon(expected, src, abs_k, n);  /* no alias */
            m4t_shift3_div_neon(inplace, inplace, abs_k, n);  /* dst == src */
            for (int i = 0; i < n; i++) {
                if (expected[i] != inplace[i]) {
                    alias_fails++;
                    if (alias_fails <= 3) {
                        fprintf(stderr,
                            "  ALIAS FAIL k=%d n=%d i=%d in=%d expected=%d inplace=%d\n",
                            abs_k, n, i, (int)src[i],
                            (int)expected[i], (int)inplace[i]);
                    }
                }
            }
            printf("  alias k=%2d n=%2d : %s\n", abs_k, n,
                   alias_fails == 0 ? "PASS" : "FAIL");
            free(src); free(expected); free(inplace);
        }
    }
    if (alias_fails > 0) {
        printf("\nFAIL: %d aliasing mismatches\n", alias_fails);
        g_fails += alias_fails;
    }
}

/* G5: perf comparison with discipline.
 *   - Workload shape declared per measurement
 *   - Min-of-5 sample (each sample = 200 iter * n elems)
 *   - Two shapes: BATCHED (one big call, n=4096) and TIGHT-LOOP (many small
 *     calls, n=4 with per-call overhead dominating). Per V4-residual-3
 *     methodology: report each shape; let consumer pick. */
typedef double (*shift3_fn)(m4t_mtfp_t*, const m4t_mtfp_t*, int, int);

static double sample_scalar(m4t_mtfp_t* out, const m4t_mtfp_t* in,
                            int abs_k, int n, int call_count) {
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (int c = 0; c < call_count; c++)
        m4t_mtfp_shift3(out, in, -abs_k, n);
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double ns = ((t1.tv_sec - t0.tv_sec) * 1e9
                  + (t1.tv_nsec - t0.tv_nsec));
    return ns / ((double)call_count * n);
}
static double sample_neon(m4t_mtfp_t* out, const m4t_mtfp_t* in,
                          int abs_k, int n, int call_count) {
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (int c = 0; c < call_count; c++)
        m4t_shift3_div_neon(out, in, abs_k, n);
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double ns = ((t1.tv_sec - t0.tv_sec) * 1e9
                  + (t1.tv_nsec - t0.tv_nsec));
    return ns / ((double)call_count * n);
}

static void perf_compare(int abs_k, int n, int call_count, const char* shape) {
    m4t_mtfp_t* in_buf  = malloc(n * sizeof(m4t_mtfp_t));
    m4t_mtfp_t* out_buf = malloc(n * sizeof(m4t_mtfp_t));
    if (!in_buf || !out_buf) { fprintf(stderr, "malloc fail\n"); exit(1); }
    srand(123 + abs_k * 17);
    for (int i = 0; i < n; i++) {
        int64_t r = ((int64_t)rand() << 32) ^ rand();
        in_buf[i] = (m4t_mtfp_t)(r % (2 * MAX_VAL + 1) - MAX_VAL);
    }

    /* Warm up. */
    for (int t = 0; t < 5; t++) {
        m4t_mtfp_shift3(out_buf, in_buf, -abs_k, n);
        m4t_shift3_div_neon(out_buf, in_buf, abs_k, n);
    }

    /* Min-of-5 for each path. */
    double scalar_min = 1e18, neon_min = 1e18;
    for (int s = 0; s < 5; s++) {
        double sc = sample_scalar(out_buf, in_buf, abs_k, n, call_count);
        double ne = sample_neon  (out_buf, in_buf, abs_k, n, call_count);
        if (sc < scalar_min) scalar_min = sc;
        if (ne < neon_min)   neon_min   = ne;
    }
    printf("  shape=%-13s k=%2d n=%4d calls=%d : scalar=%.2f ns/elem  "
           "neon=%.2f ns/elem  speedup=%.1fx\n",
           shape, abs_k, n, call_count, scalar_min, neon_min,
           scalar_min / neon_min);
    free(in_buf); free(out_buf);
}

/* G1: Exhaustive NEON-vs-scalar verify — sweep every x in [-MAX_VAL, +MAX_VAL]
 * for every k ∈ [1, 19], confirm bit-exact match. 2.2 × 10¹⁰ test points. */
static int exhaustive_verify_per_k(int abs_k) {
    enum { CHUNK = 65536 };  /* batch through the kernel for speed */
    m4t_mtfp_t* in_buf  = malloc(CHUNK * sizeof(m4t_mtfp_t));
    m4t_mtfp_t* out_neon = malloc(CHUNK * sizeof(m4t_mtfp_t));
    m4t_mtfp_t* out_ref  = malloc(CHUNK * sizeof(m4t_mtfp_t));
    if (!in_buf || !out_neon || !out_ref) {
        fprintf(stderr, "malloc fail\n"); exit(1);
    }
    int64_t per_k_fails = 0;
    int64_t total = 0;

    for (int64_t base = -MAX_VAL; base <= MAX_VAL; base += CHUNK) {
        int n = (int)(base + CHUNK <= MAX_VAL + 1
                          ? CHUNK
                          : (MAX_VAL + 1 - base));
        for (int j = 0; j < n; j++) in_buf[j] = (m4t_mtfp_t)(base + j);
        m4t_shift3_div_neon(out_neon, in_buf, abs_k, n);
        m4t_mtfp_shift3(out_ref, in_buf, -abs_k, n);
        for (int j = 0; j < n; j++) {
            if (out_neon[j] != out_ref[j]) {
                per_k_fails++;
                if (per_k_fails <= 3) {
                    fprintf(stderr,
                        "  k=%d EXHAUSTIVE FAIL x=%d neon=%d ref=%d\n",
                        abs_k, (int)in_buf[j], (int)out_neon[j], (int)out_ref[j]);
                }
            }
        }
        total += n;
    }
    free(in_buf); free(out_neon); free(out_ref);
    if (per_k_fails == 0) {
        printf("  k=%2d EXHAUSTIVE PASS (%lld bit-exact)\n",
               abs_k, (long long)total);
        return 0;
    }
    printf("  k=%2d EXHAUSTIVE FAIL (%lld / %lld mismatches)\n",
           abs_k, (long long)per_k_fails, (long long)total);
    return 1;
}

int main(int argc, char** argv) {
    int do_exhaustive = (argc > 1 && argv[1][0] == 'x');

    printf("=== Bit-exact (sample): NEON vs m4t_mtfp_shift3 (scalar) ===\n");
    for (int k = 1; k <= 19; k++) test_bit_exact_per_k(k);
    if (g_fails > 0) {
        printf("\nFAIL: %d total mismatches across all k (sample)\n", g_fails);
        return 1;
    }
    printf("\nPASS: 19/19 k values bit-exact across boundary + random sample\n");

    printf("\n=== G3: Aliasing test (dst == src) ===\n");
    test_aliasing();
    if (g_fails > 0) {
        printf("\nFAIL: aliasing test\n");
        return 1;
    }

    if (do_exhaustive) {
        printf("\n=== G1: Exhaustive NEON-vs-scalar (1.16e9 per k × 19 k) ===\n");
        int total_fails = 0;
        for (int k = 1; k <= 19; k++) total_fails += exhaustive_verify_per_k(k);
        if (total_fails > 0) {
            printf("\nFAIL: %d k values had exhaustive mismatches\n", total_fails);
            return 1;
        }
        printf("\nPASS: 19/19 k values exhaustively bit-exact\n");
    } else {
        printf("\n(pass 'x' as arg to also run G1 exhaustive verify)\n");
    }

    printf("\n=== G5: Perf comparison (min-of-5 per measurement) ===\n");
    printf("Shape A (BATCHED): one call, n=4096 — represents bulk divide.\n");
    for (int k = 1; k <= 19; k += 6)
        perf_compare(k, 4096, 200, "BATCHED");
    printf("\n");
    printf("Shape B (TIGHT-LOOP): n=4 per call, many calls — per-call overhead bound.\n");
    for (int k = 1; k <= 19; k += 6)
        perf_compare(k, 4, 200000, "TIGHT-LOOP");

    return 0;
}
