/*
 * m4t_lut_gen.c — host-side LUT generator for M4T GELU and exp tables.
 *
 * This tool runs on a dev machine, computes lookup tables using float
 * math (expf, tanhf), and emits a .c file containing the tables as
 * compile-time const arrays. The output is committed to the repo and
 * linked into libm4t.a. The generator itself is NOT linked into libm4t.
 *
 * This is the ONLY place in the entire M4T/glyph ecosystem where float
 * arithmetic is permitted, and it runs at build time, not at runtime.
 *
 * Build: cc -o m4t_lut_gen m4t/tools/m4t_lut_gen.c -lm
 * Run:   ./m4t_lut_gen > m4t/src/m4t_mtfp_tables.c
 */

#include <stdio.h>
#include <math.h>
#include <stdint.h>

/* Mirror the canonical constants from m4t_types.h so they stay in sync.
 * The generator is a standalone host tool and does not #include m4t_types.h
 * (which may require aarch64 headers). Instead we derive from the same
 * formula: SCALE = 3^10, MAX_VAL = (3^19 - 1) / 2. */
#define MTFP_SCALE       59049          /* 3^10 */
#define MTFP_INV_SCALE   (1.0f / 59049.0f)
#define MTFP_MAX_VAL     581130733      /* (3^19 - 1) / 2 — must match M4T_MTFP_MAX_VAL */

/* Table range: [-6.0, +6.0] in real units.
 * In MTFP cell units: [-6 * SCALE, +6 * SCALE] = [-354294, +354294].
 * Table size: 2 * 354294 + 1 = 708589 entries. */
#define TABLE_HALF    354294
#define TABLE_SIZE    (2 * TABLE_HALF + 1)

static int32_t mtfp_from_float(float x) {
    float scaled = x * (float)MTFP_SCALE;
    int32_t rounded = (int32_t)lrintf(scaled);
    if (rounded > MTFP_MAX_VAL) rounded = MTFP_MAX_VAL;
    if (rounded < -MTFP_MAX_VAL) rounded = -MTFP_MAX_VAL;
    return rounded;
}

static float gelu_f32(float x) {
    float c = 0.7978845608f;
    return 0.5f * x * (1.0f + tanhf(c * (x + 0.044715f * x * x * x)));
}

static void emit_table(const char* name, const char* comment,
                       int32_t* table, int size, int entries_per_line) {
    printf("/* %s\n", comment);
    printf(" * Range: [-6.0, +6.0] in real units = [-%d, +%d] in MTFP cells.\n", TABLE_HALF, TABLE_HALF);
    printf(" * Size: %d entries, %d bytes.\n", size, size * 4);
    printf(" * Generated by m4t_lut_gen.c — do not hand-edit. */\n");
    printf("const m4t_mtfp_t %s[M4T_LUT_TABLE_SIZE] = {\n", name);
    for (int i = 0; i < size; i++) {
        if (i % entries_per_line == 0) printf("    ");
        printf("%d", table[i]);
        if (i < size - 1) printf(",");
        if (i % entries_per_line == entries_per_line - 1 || i == size - 1)
            printf("\n");
        else
            printf(" ");
    }
    printf("};\n\n");
}

int main(void) {
    static int32_t gelu_table[TABLE_SIZE];
    static int32_t exp_table[TABLE_SIZE];

    /* Compute GELU table */
    for (int i = 0; i < TABLE_SIZE; i++) {
        int32_t repr = i - TABLE_HALF;
        float x = (float)repr * MTFP_INV_SCALE;
        gelu_table[i] = mtfp_from_float(gelu_f32(x));
    }

    /* Compute exp table */
    for (int i = 0; i < TABLE_SIZE; i++) {
        int32_t repr = i - TABLE_HALF;
        float x = (float)repr * MTFP_INV_SCALE;
        float y = expf(x);
        exp_table[i] = mtfp_from_float(y);
    }

    /* Emit header */
    printf("/*\n");
    printf(" * m4t_mtfp_tables.c — pre-computed GELU and exp lookup tables for M4T.\n");
    printf(" *\n");
    printf(" * AUTO-GENERATED by tools/m4t_lut_gen.c — do not hand-edit.\n");
    printf(" * Regenerate with: ./m4t_lut_gen > src/m4t_mtfp_tables.c\n");
    printf(" *\n");
    printf(" * These tables are the ONLY place in libm4t where values derived from\n");
    printf(" * float arithmetic appear. They are computed offline by the generator\n");
    printf(" * and stored as const MTFP cells. The runtime never touches float.\n");
    printf(" */\n\n");
    printf("#include \"m4t_types.h\"\n\n");
    printf("#define M4T_LUT_TABLE_HALF  %d\n", TABLE_HALF);
    printf("#define M4T_LUT_TABLE_SIZE  %d\n\n", TABLE_SIZE);

    emit_table("m4t_gelu_table",
               "GELU(x) lookup. Index = cell + TABLE_HALF. Clamp at boundaries.",
               gelu_table, TABLE_SIZE, 12);

    emit_table("m4t_exp_table",
               "exp(x) lookup for softmax. Index = cell + TABLE_HALF. Clamp at boundaries.",
               exp_table, TABLE_SIZE, 12);

    /* Emit boundary constants for the runtime lookup functions */
    printf("/* Pre-computed clamp values for exp(+6) and GELU saturation. */\n");
    printf("const m4t_mtfp_t m4t_exp_clamp_hi  = %d;  /* exp(6.0) in MTFP */\n",
           mtfp_from_float(expf(6.0f)));
    printf("const m4t_mtfp_t m4t_gelu_clamp_hi = %d;  /* 6.0 in MTFP (GELU(x)≈x for large x) */\n",
           mtfp_from_float(6.0f));

    /* Print stats to stderr */
    fprintf(stderr, "m4t_lut_gen: generated %d GELU + %d exp entries\n", TABLE_SIZE, TABLE_SIZE);
    fprintf(stderr, "m4t_lut_gen: total .rodata: %d bytes (%.2f MB)\n",
            TABLE_SIZE * 4 * 2, (float)(TABLE_SIZE * 4 * 2) / (1024.0f * 1024.0f));

    return 0;
}
