/*
 * glyph_mtfp.h — Multi-Trit Floating Point arithmetic
 *
 * GLYPH IS TERNARY / MULTI-TRIT / MULTI-TRIT FLOATING POINT ONLY.
 *
 * This header declares the MTFP numeric core of glyph. Every function here
 * operates on glyph_mtfp_t cells only. There is no float path, no int8
 * numeric operand, and no LUT-backed nonlinearity in this version of the
 * file. softmax and gelu are deferred to a later pass that ships a
 * compile-time-constant LUT generated by a host-side tool.
 */

#ifndef GLYPH_MTFP_H
#define GLYPH_MTFP_H

#include "glyph_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ── Scalar arithmetic ─────────────────────────────────────────────────── */

/* All scalar arithmetic saturates at ±GLYPH_MTFP_MAX_VAL. This is a hard
 * API contract: the output of every MTFP operation is a valid MTFP cell,
 * even when the true mathematical result would exceed the range. */

static inline glyph_mtfp_t glyph_mtfp_clamp64(int64_t v) {
    if (v >  (int64_t)GLYPH_MTFP_MAX_VAL) return  GLYPH_MTFP_MAX_VAL;
    if (v < -(int64_t)GLYPH_MTFP_MAX_VAL) return -GLYPH_MTFP_MAX_VAL;
    return (glyph_mtfp_t)v;
}

static inline glyph_mtfp_t glyph_mtfp_add(glyph_mtfp_t a, glyph_mtfp_t b) {
    return glyph_mtfp_clamp64((int64_t)a + (int64_t)b);
}

static inline glyph_mtfp_t glyph_mtfp_sub(glyph_mtfp_t a, glyph_mtfp_t b) {
    return glyph_mtfp_clamp64((int64_t)a - (int64_t)b);
}

static inline glyph_mtfp_t glyph_mtfp_neg(glyph_mtfp_t a) {
    /* Safe for in-range inputs: |-MAX_VAL| = MAX_VAL. */
    return -a;
}

/* Multi-trit × multi-trit multiply. int64 product, rescale by SCALE,
 * round to nearest with ties away from zero, saturate at ±MAX_VAL.
 *
 * Saturation is a hard requirement: the product of two in-range MTFP cells
 * can legitimately exceed ±MAX_VAL (e.g. 2.0 * 2.0 = 4.0, well below
 * ±18183). Callers must still only pass in-range operands; this routine
 * keeps the output in range even when the true mathematical product
 * wouldn't fit. */
static inline glyph_mtfp_t glyph_mtfp_mul(glyph_mtfp_t a, glyph_mtfp_t b) {
    int64_t prod = (int64_t)a * (int64_t)b;
    if (prod >= 0) prod += GLYPH_MTFP_SCALE / 2;
    else           prod -= GLYPH_MTFP_SCALE / 2;
    int64_t q = prod / GLYPH_MTFP_SCALE;
    if (q >  (int64_t)GLYPH_MTFP_MAX_VAL) q =  GLYPH_MTFP_MAX_VAL;
    if (q < -(int64_t)GLYPH_MTFP_MAX_VAL) q = -GLYPH_MTFP_MAX_VAL;
    return (glyph_mtfp_t)q;
}

/* Multi-trit × single trit. Zero multiplies: the compiler reduces a
 * multiply by {-1,0,+1} to a negate or a drop. */
static inline glyph_mtfp_t glyph_mtfp_mul_trit(glyph_mtfp_t a, glyph_trit_t t) {
    return a * (int32_t)t;
}

/* ── Vector arithmetic ─────────────────────────────────────────────────── */

void glyph_mtfp_vec_zero(glyph_mtfp_t* x, int n);
void glyph_mtfp_vec_add(glyph_mtfp_t* dst, const glyph_mtfp_t* a, const glyph_mtfp_t* b, int n);
void glyph_mtfp_vec_add_inplace(glyph_mtfp_t* dst, const glyph_mtfp_t* a, int n);
void glyph_mtfp_vec_scale(glyph_mtfp_t* dst, const glyph_mtfp_t* src, glyph_mtfp_t scale, int n);

/* ── Dense MTFP × MTFP matmul (int64 accumulator, rescale by SCALE) ──────
 *
 * glyph_mtfp_matmul:     Y[M,N] = X[M,K] @ W[K,N]
 * glyph_mtfp_matmul_bt:  Y[M,N] = X[M,K] @ W[N,K]^T   (W row-major with K stride)
 */
void glyph_mtfp_matmul(
    glyph_mtfp_t* Y,
    const glyph_mtfp_t* X,
    const glyph_mtfp_t* W,
    int M, int K, int N
);

void glyph_mtfp_matmul_bt(
    glyph_mtfp_t* Y,
    const glyph_mtfp_t* X,
    const glyph_mtfp_t* W,
    int M, int K, int N
);

/* ── Bias / normalization ──────────────────────────────────────────────── */

void glyph_mtfp_bias_add(glyph_mtfp_t* x, const glyph_mtfp_t* b, int batch, int dim);

/* Divide each element by isqrt(fan_in). Used before nonlinearities to
 * keep values in the table-lookup range. */
void glyph_mtfp_fan_in_normalize(glyph_mtfp_t* x, int n, int fan_in);

/* LayerNorm, forward only (inference-only v0).
 *
 * `eps` is an MTFP cell in real units (e.g. glyph_mtfp_from_real_hostside(1e-5)
 * if you generated weights offline). The function squares it internally for
 * comparison against variance. */
void glyph_mtfp_layernorm(
    glyph_mtfp_t* dst,
    const glyph_mtfp_t* src,
    const glyph_mtfp_t* weight,
    const glyph_mtfp_t* bias,
    glyph_mtfp_t eps,
    int rows, int cols
);

/* ── Integer square-root helpers ───────────────────────────────────────── */

/* floor(sqrt(x)) for x >= 0, via Newton-Raphson. Pure integer. */
int64_t glyph_isqrt64(int64_t x);

/* Returns SCALE^2 / sqrt(x). x is a variance in SCALE^2 units; result is
 * an rstd in SCALE units. Pure integer, used by layernorm. */
int64_t glyph_mtfp_isqrt_inv(int64_t x);

#ifdef __cplusplus
}
#endif

#endif /* GLYPH_MTFP_H */
